# Generated by Django 5.2.5 on 2025-08-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, verbose_name='введите никнейм')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='введите емаил')),
                ('phone_number', models.CharField(max_length=15)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_image')),
                ('address', models.CharField(max_length=200)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
